<div style="background: url('css/images/bg.jpg') 50% 40px; border-radius:20px; height:250px;">
<table width='100%' style='margin-top:-20px;'>
<tr>
	<td style='height:200px;font-size:25px; text-align:center; color:#3a3a3a;'>
	<img src='/css/images/header_graphic.png'>
	</td>
	<td style='width:450px;text-align:center;'>
	<h1>Grab the Latest Version!</h1><br><br>
	<a href='https://github.com/jamstarter/SwyftPHP/zipball/master' class='download_button'>Download (.zip)</a>
	<br><br><br>Current Release: v<?=$this->version;?> 
	</td>
</tr>
</table>
</div>
<h1>Don't let your framework define your style</h1>
<p>
	Swyft is an Open Source PHP Framework that packs a punch. With a small footprint, easy configuration and simple syntax, Swyft can be used for applications of any scale.
	It is easy to customize and easy to extend with libraries from other frameworks, like Zend or CodeIgniter. Swyft was designed with three things in mind:
	<ul>
		<li><b>Keep it Small</b> - There's no need for libraries taking up space and resources if we never use them</li> 
		<li><b>Keep it Simple</b> - PHP doesn't need to be difficult. Do things the way that makes sense</li>
		<li><b>Keep it Flexible</b> - Easily reuse code. Just drop a class file in the library and its instantly integrated!</li>
	</ul>
</p>
<div style='text-align:center;'>
	<img src="css/images/icons.jpg">
</div>