<a href='/docs'>Back to Documentation</a>
<h1>Database Migrations</h1>
<p>Database migrations are useful for a number of reasons. Using migrations will help developers working in a team environment share the same database schema without
having to email SQL queries back and forth. It also allows developers to "roll back" to previous database versions and track changes to your database over time. Use the
instructions below to get started running migrations.</p>
<h2>Creating a Migration Script</h2>
<p>Migrations are just PHP classes with <b>up()</b> and <b>down()</b> functions. When you are upgrading to a higher version number for your database, the up functions will
be run. When downgrading, the down function will be run. Migrations are run in numerical order. All migration classes use the naming convention of <b>Migration_#</b> for the
class name. See the structure below for Migration_1.</p>
scripts/migrations/Migration_1.php
<xmp>class Migration_1 extends Swyft_DB{

	protected $_name = "users";

	public function up(){
		$this->addColumn('username');
		->addColumn('phone','int(11)');
		->addColumn('password');
		->createTable('users');	
	}
	
	public function down(){
		$this->dropTable('users');
	}

}</xmp>
<p>You can include any logic in the up and down functions. However, it is recommended that these be opposites of each other to allow you to upgrade and downgrade your
system. There is no reason that these function only contain actions to alter the database, but its a good idea to make sure that any extra business logic you include
is relevant to the migration.</p>

<h2>Running Migrations</h2>
<p>Migrations are run via the command line interface. First, you need to cd into the scripts directory.</p>
<xmp>cd scripts</xmp>
<p>Then, just run the migrate command to upgrade to the most current version.</p>
<xmp>>> php cli.php migrate
Swyft Database Migration 

Migrated to Version: 3
</xmp>
<p>To upgrade or downgrade to a specific version number, simply append the version number to the end of the command.</p>
<xmp>php cli.php migrate 1
Swyft Database Migration 

Migrated to Version: 1
</xmp>
<h2>Check Current Version</h2>
<p>You can check what version your database is currently set to by running <b>migrationversion</b>:</p>
<xmp>>> php cli.php migrationversion
Current Database Version: 3
</xmp>
<p>The migration version is also written to a file located at <b>scripts/migration.ini</b>. If you are using migrations to help organize a team of developers, make sure 
you <b>gitignore</b> or equivalent for the migration.ini file to avoid falsely updating your migration number when you pull changes from your team.<br><br>
<a href='https://help.github.com/articles/ignoring-files' target="_blank">More information on ignoring files</a></p>