<!DOCTYPE >
<html>
	<head>
		<link href='http://fonts.googleapis.com/css?family=Titan+One' rel='stylesheet' type='text/css'>
		<link rel='stylesheet' type='text/css' href='/css/global.css'>
		<title>Swyft: Open Source PHP Framework<? if(@$pageTitle){ echo "::" . @$pageTitle; } ?></title>
	</head>
	<body>
		<div id='header_wrapper'>
			<div id='header'>	
			<div id='navbar'>
				<a href='/'>Home</a>
				<a href='/docs'>Documentation</a>
			</div>
			<img src='/css/images/logo.png' id='logo'>	
			</div>
		</div>
		<div id='content_wrapper'>
			<div id='content'>
				<?=$swyftPageContent;?>
			</div>
		</div>
		<div id='footer_wrapper'>
			<div id='footer'>
			</div>
		</div>
	</body>
</html>