<!DOCTYPE html>
<html>
	<head>
		<link href='http://fonts.googleapis.com/css?family=Titan+One' rel='stylesheet' type='text/css'>
		<link rel='stylesheet' type='text/css' href='/css/global.css'>
		<title>Swyft: Open Source PHP Framework<? if(@$pageTitle){ echo "::" . @$pageTitle; } ?></title>
	</head>
	<body>
		<div id='header_wrapper'>
			<div id='header'>	
			<div id='navbar'>
				<a href='/'>Home</a>
				<a href='/docs'>Documentation</a>
				<? if(Swyft_User::isActive()){ ?>
				<a href='/logout'>Logout</a>
				<? } else { ?>
				<a href='/login'>Login</a>
				<? } ?>
			</div>
			<a href='/'><img src='/css/images/logo.png' id='logo' border='0'></a>
			</div>
		</div>
		<div id='content_wrapper'>
			<div id='content'>
				<?=$swyftPageContent;?>
			</div>
		</div>
		<div id='footer_wrapper'>
			<div id='footer'>
			</div>
		</div>
	</body>
	<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-32518830-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<script type="text/javascript" charset="utf-8">
  var is_ssl = ("https:" == document.location.protocol);
  var asset_host = is_ssl ? "https://d3rdqalhjaisuu.cloudfront.net/" : "http://d3rdqalhjaisuu.cloudfront.net/";
  document.write(unescape("%3Cscript src='" + asset_host + "javascripts/feedback-v2.js' type='text/javascript'%3E%3C/script%3E"));
</script>

<script type="text/javascript" charset="utf-8">
  var feedback_widget_options = {};

  feedback_widget_options.display = "overlay";  
  feedback_widget_options.company = "swyftphp";
  feedback_widget_options.placement = "left";
  feedback_widget_options.color = "#222";
  feedback_widget_options.style = "idea";
  
  
  
  
  
  
  

  var feedback_widget = new GSFN.feedback_widget(feedback_widget_options);
</script>

</html>