<!DOCTYPE html>
<html>
	<head>
		<link href='http://fonts.googleapis.com/css?family=Titan+One' rel='stylesheet' type='text/css'>
		<link rel='stylesheet' type='text/css' href='/css/global.css'>
		<title>Swyft: Open Source PHP Framework<? if(@$pageTitle){ echo "::" . @$pageTitle; } ?></title>
	</head>
	<body>
		<div id='header_wrapper'>
			<div id='header'>	
			<div id='navbar'>
				<a href='/'>Home</a>
				<a href='/docs'>Documentation</a>
			</div>
			<a href='/'><img src='/css/images/logo.png' id='logo' border='0'></a>
			</div>
		</div>
		<div id='content_wrapper'>
			<div id='content'>
				<?=$swyftPageContent;?>
			</div>
		</div>
		<div id='footer_wrapper'>
			<div id='footer'>
			</div>
		</div>
	</body>
	<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-32518830-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</html>